vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        files:
            uri_prefix: /uploads/fichiers
            upload_destination: '%kernel.project_dir%/uploads/fichiers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
