controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

authentication_token:
  path: /api/authentication_token
  methods: ['POST']

registration:
    path: /api/register
    controller: App\Controller\RegistrationController::registerapi
    methods: ['POST']
    stateless: false
